<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Unity_new_overlay</RootNamespace>
    <AssemblyName>$00-Unity Team Stream</AssemblyName>
    <ApplicationIcon>wwwroot\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\GlobalShared\Scripts\Riverbank.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\GlobalShared\assets\teamLogos\" />
  </ItemGroup>

</Project>
